"""initial_schema

Revision ID: dfa1712dd3e2
Revises: 
Create Date: 2026-02-23 19:41:33.962117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa1712dd3e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_group',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_group_slug'), 'content_group', ['slug'], unique=True)
    op.create_table('speaker_stat_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speaker_stat_group_key'), 'speaker_stat_group', ['key'], unique=True)
    op.create_table('speaker_profile',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('surname', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('photo_key', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['content_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'slug', name='uq_speaker_profile_group_slug')
    )
    op.create_index(op.f('ix_speaker_profile_slug'), 'speaker_profile', ['slug'], unique=False)
    op.create_table('speaker_stat_definition',
    sa.Column('stat_key', sa.String(length=64), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['speaker_stat_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stat_key')
    )
    op.create_table('transcript',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_uri', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('video_path', sa.String(length=1024), nullable=True),
    sa.Column('speakers_count', sa.Integer(), nullable=True),
    sa.Column('stats_total_words', sa.Integer(), nullable=True),
    sa.Column('stats_segment_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['content_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_source_uri'), 'transcript', ['source_uri'], unique=True)
    op.create_table('segment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transcript_id', sa.String(length=36), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('speaker_id_in_transcript', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcript.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('speaker_mapping',
    sa.Column('transcript_id', sa.String(length=36), nullable=False),
    sa.Column('speaker_id_in_transcript', sa.String(length=64), nullable=False),
    sa.Column('speaker_profile_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['speaker_profile_id'], ['speaker_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcript.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transcript_id', 'speaker_id_in_transcript'),
    sa.UniqueConstraint('transcript_id', 'speaker_id_in_transcript', name='uq_transcript_speaker')
    )
    op.create_table('transcript_speaker_stats',
    sa.Column('transcript_id', sa.String(length=36), nullable=False),
    sa.Column('speaker_id_in_transcript', sa.String(length=64), nullable=False),
    sa.Column('total_seconds', sa.Float(), nullable=False),
    sa.Column('segment_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('wpm', sa.Float(), nullable=True),
    sa.Column('avg_segment_duration_sec', sa.Float(), nullable=True),
    sa.Column('shortest_talk_sec', sa.Float(), nullable=True),
    sa.Column('longest_talk_sec', sa.Float(), nullable=True),
    sa.Column('median_segment_duration_sec', sa.Float(), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=True),
    sa.Column('avg_turn_length_sec', sa.Float(), nullable=True),
    sa.Column('avg_turn_length_segments', sa.Float(), nullable=True),
    sa.Column('is_first_speaker', sa.Boolean(), nullable=False),
    sa.Column('is_last_speaker', sa.Boolean(), nullable=False),
    sa.Column('share_speaking_time', sa.Float(), nullable=True),
    sa.Column('share_words', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcript.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transcript_id', 'speaker_id_in_transcript'),
    sa.UniqueConstraint('transcript_id', 'speaker_id_in_transcript', name='uq_transcript_speaker_stats')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcript_speaker_stats')
    op.drop_table('speaker_mapping')
    op.drop_table('segment')
    op.drop_index(op.f('ix_transcript_source_uri'), table_name='transcript')
    op.drop_table('transcript')
    op.drop_table('speaker_stat_definition')
    op.drop_index(op.f('ix_speaker_profile_slug'), table_name='speaker_profile')
    op.drop_table('speaker_profile')
    op.drop_index(op.f('ix_speaker_stat_group_key'), table_name='speaker_stat_group')
    op.drop_table('speaker_stat_group')
    op.drop_index(op.f('ix_content_group_slug'), table_name='content_group')
    op.drop_table('content_group')
    # ### end Alembic commands ###
