"""initial_schema

Revision ID: ea2adb546043
Revises: 
Create Date: 2026-02-20 11:38:37.719250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea2adb546043'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaker_profile',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speaker_profile_slug'), 'speaker_profile', ['slug'], unique=True)
    op.create_table('transcript',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_uri', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('video_path', sa.String(length=1024), nullable=True),
    sa.Column('speakers_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_source_uri'), 'transcript', ['source_uri'], unique=True)
    op.create_table('segment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transcript_id', sa.String(length=36), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('speaker_id_in_transcript', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcript.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('speaker_mapping',
    sa.Column('transcript_id', sa.String(length=36), nullable=False),
    sa.Column('speaker_id_in_transcript', sa.String(length=64), nullable=False),
    sa.Column('speaker_profile_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['speaker_profile_id'], ['speaker_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcript.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transcript_id', 'speaker_id_in_transcript'),
    sa.UniqueConstraint('transcript_id', 'speaker_id_in_transcript', name='uq_transcript_speaker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speaker_mapping')
    op.drop_table('segment')
    op.drop_index(op.f('ix_transcript_source_uri'), table_name='transcript')
    op.drop_table('transcript')
    op.drop_index(op.f('ix_speaker_profile_slug'), table_name='speaker_profile')
    op.drop_table('speaker_profile')
    # ### end Alembic commands ###
